/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BossNPC = IDL.Record({
  'baseHp' : IDL.Nat,
  'shieldCooldownUntil' : Time,
  'wallHp' : IDL.Nat,
  'serverId' : IDL.Nat,
  'defeated' : IDL.Bool,
});
export const Troops = IDL.Record({
  'tanks' : IDL.Nat,
  'jets' : IDL.Nat,
  'soldiers' : IDL.Nat,
});
export const Player = IDL.Record({
  'hp' : IDL.Nat,
  'id' : IDL.Principal,
  'upgradeLevel' : IDL.Nat,
  'username' : IDL.Text,
  'resources' : IDL.Record({
    'food' : IDL.Nat,
    'wood' : IDL.Nat,
    'stone' : IDL.Nat,
  }),
  'posX' : IDL.Float64,
  'posY' : IDL.Float64,
  'troops' : Troops,
  'baseHp' : IDL.Nat,
  'shieldCooldownUntil' : Time,
  'level' : IDL.Nat,
  'shieldActive' : IDL.Bool,
  'wallHp' : IDL.Nat,
  'lastSeen' : Time,
  'serverId' : IDL.Nat,
});
export const ServerInfo = IDL.Record({
  'name' : IDL.Text,
  'playerCount' : IDL.Nat,
  'isOnline' : IDL.Bool,
});

export const idlService = IDL.Service({
  'attackBossNPC' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'claimTerritory' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'createClan' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'getBossNPC' : IDL.Func([IDL.Nat], [BossNPC], []),
  'getPlayer' : IDL.Func([IDL.Principal], [Player], ['query']),
  'getPlayersOnServer' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], []),
  'getServerInfo' : IDL.Func([IDL.Nat], [ServerInfo], ['query']),
  'healPlayerWall' : IDL.Func([IDL.Nat], [], []),
  'initializeResourceFields' : IDL.Func([IDL.Nat], [], []),
  'joinClan' : IDL.Func([IDL.Nat], [], []),
  'recordAttack' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'registerOrUpdatePlayer' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'sendChatMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'setPlayerShield' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'updateTroops' : IDL.Func([Troops], [], []),
  'upgradeBase' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BossNPC = IDL.Record({
    'baseHp' : IDL.Nat,
    'shieldCooldownUntil' : Time,
    'wallHp' : IDL.Nat,
    'serverId' : IDL.Nat,
    'defeated' : IDL.Bool,
  });
  const Troops = IDL.Record({
    'tanks' : IDL.Nat,
    'jets' : IDL.Nat,
    'soldiers' : IDL.Nat,
  });
  const Player = IDL.Record({
    'hp' : IDL.Nat,
    'id' : IDL.Principal,
    'upgradeLevel' : IDL.Nat,
    'username' : IDL.Text,
    'resources' : IDL.Record({
      'food' : IDL.Nat,
      'wood' : IDL.Nat,
      'stone' : IDL.Nat,
    }),
    'posX' : IDL.Float64,
    'posY' : IDL.Float64,
    'troops' : Troops,
    'baseHp' : IDL.Nat,
    'shieldCooldownUntil' : Time,
    'level' : IDL.Nat,
    'shieldActive' : IDL.Bool,
    'wallHp' : IDL.Nat,
    'lastSeen' : Time,
    'serverId' : IDL.Nat,
  });
  const ServerInfo = IDL.Record({
    'name' : IDL.Text,
    'playerCount' : IDL.Nat,
    'isOnline' : IDL.Bool,
  });
  
  return IDL.Service({
    'attackBossNPC' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'claimTerritory' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'createClan' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'getBossNPC' : IDL.Func([IDL.Nat], [BossNPC], []),
    'getPlayer' : IDL.Func([IDL.Principal], [Player], ['query']),
    'getPlayersOnServer' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], []),
    'getServerInfo' : IDL.Func([IDL.Nat], [ServerInfo], ['query']),
    'healPlayerWall' : IDL.Func([IDL.Nat], [], []),
    'initializeResourceFields' : IDL.Func([IDL.Nat], [], []),
    'joinClan' : IDL.Func([IDL.Nat], [], []),
    'recordAttack' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'registerOrUpdatePlayer' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'sendChatMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'setPlayerShield' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'updateTroops' : IDL.Func([Troops], [], []),
    'upgradeBase' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };