/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BossNPC {
  'baseHp' : bigint,
  'shieldCooldownUntil' : Time,
  'wallHp' : bigint,
  'serverId' : bigint,
  'defeated' : boolean,
}
export interface Player {
  'hp' : bigint,
  'id' : Principal,
  'upgradeLevel' : bigint,
  'username' : string,
  'resources' : { 'food' : bigint, 'wood' : bigint, 'stone' : bigint },
  'posX' : number,
  'posY' : number,
  'troops' : Troops,
  'baseHp' : bigint,
  'shieldCooldownUntil' : Time,
  'level' : bigint,
  'shieldActive' : boolean,
  'wallHp' : bigint,
  'lastSeen' : Time,
  'serverId' : bigint,
}
export interface ServerInfo {
  'name' : string,
  'playerCount' : bigint,
  'isOnline' : boolean,
}
export type Time = bigint;
export interface Troops {
  'tanks' : bigint,
  'jets' : bigint,
  'soldiers' : bigint,
}
export interface _SERVICE {
  'attackBossNPC' : ActorMethod<[bigint, bigint], undefined>,
  'claimTerritory' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
  'createClan' : ActorMethod<[string, string, bigint], bigint>,
  'getBossNPC' : ActorMethod<[bigint], BossNPC>,
  'getPlayer' : ActorMethod<[Principal], Player>,
  'getPlayersOnServer' : ActorMethod<[bigint], Array<Player>>,
  'getServerInfo' : ActorMethod<[bigint], ServerInfo>,
  'healPlayerWall' : ActorMethod<[bigint], undefined>,
  'initializeResourceFields' : ActorMethod<[bigint], undefined>,
  'joinClan' : ActorMethod<[bigint], undefined>,
  'recordAttack' : ActorMethod<
    [string, string, bigint, string, bigint, bigint],
    undefined
  >,
  'registerOrUpdatePlayer' : ActorMethod<
    [string, bigint, number, number],
    undefined
  >,
  'sendChatMessage' : ActorMethod<[bigint, string, string], undefined>,
  'setPlayerShield' : ActorMethod<[Principal, boolean], undefined>,
  'updateTroops' : ActorMethod<[Troops], undefined>,
  'upgradeBase' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];