/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    hp: bigint;
    id: Principal;
    upgradeLevel: bigint;
    username: string;
    resources: {
        food: bigint;
        wood: bigint;
        stone: bigint;
    };
    posX: number;
    posY: number;
    troops: Troops;
    baseHp: bigint;
    shieldCooldownUntil: Time;
    level: bigint;
    shieldActive: boolean;
    wallHp: bigint;
    lastSeen: Time;
    serverId: bigint;
}
export interface Troops {
    tanks: bigint;
    jets: bigint;
    soldiers: bigint;
}
export interface BossNPC {
    baseHp: bigint;
    shieldCooldownUntil: Time;
    wallHp: bigint;
    serverId: bigint;
    defeated: boolean;
}
export type Time = bigint;
export interface ServerInfo {
    name: string;
    playerCount: bigint;
    isOnline: boolean;
}
export interface backendInterface {
    attackBossNPC(serverId: bigint, damage: bigint): Promise<void>;
    claimTerritory(serverId: bigint, cellX: bigint, cellY: bigint, clanId: bigint): Promise<void>;
    createClan(name: string, color: string, serverId: bigint): Promise<bigint>;
    getBossNPC(serverId: bigint): Promise<BossNPC>;
    getPlayer(playerId: Principal): Promise<Player>;
    getPlayersOnServer(serverId: bigint): Promise<Array<Player>>;
    getServerInfo(serverId: bigint): Promise<ServerInfo>;
    healPlayerWall(wallHpAmount: bigint): Promise<void>;
    initializeResourceFields(serverId: bigint): Promise<void>;
    joinClan(clanId: bigint): Promise<void>;
    recordAttack(attackerUsername: string, attackerClanName: string, targetId: bigint, targetType: string, serverId: bigint, damage: bigint): Promise<void>;
    registerOrUpdatePlayer(username: string, serverId: bigint, posX: number, posY: number): Promise<void>;
    sendChatMessage(serverId: bigint, username: string, content: string): Promise<void>;
    setPlayerShield(playerId: Principal, active: boolean): Promise<void>;
    updateTroops(troops: Troops): Promise<void>;
    upgradeBase(upgradeType: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async attackBossNPC(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.attackBossNPC(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.attackBossNPC(arg0, arg1);
            return result;
        }
    }
    async claimTerritory(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimTerritory(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimTerritory(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createClan(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClan(arg0, arg1, arg2);
            return result;
        }
    }
    async getBossNPC(arg0: bigint): Promise<BossNPC> {
        if (this.processError) {
            try {
                const result = await this.actor.getBossNPC(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBossNPC(arg0);
            return result;
        }
    }
    async getPlayer(arg0: Principal): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return result;
        }
    }
    async getPlayersOnServer(arg0: bigint): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersOnServer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersOnServer(arg0);
            return result;
        }
    }
    async getServerInfo(arg0: bigint): Promise<ServerInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getServerInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServerInfo(arg0);
            return result;
        }
    }
    async healPlayerWall(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.healPlayerWall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healPlayerWall(arg0);
            return result;
        }
    }
    async initializeResourceFields(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeResourceFields(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeResourceFields(arg0);
            return result;
        }
    }
    async joinClan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinClan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinClan(arg0);
            return result;
        }
    }
    async recordAttack(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAttack(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAttack(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async registerOrUpdatePlayer(arg0: string, arg1: bigint, arg2: number, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrUpdatePlayer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrUpdatePlayer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async sendChatMessage(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async setPlayerShield(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPlayerShield(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPlayerShield(arg0, arg1);
            return result;
        }
    }
    async updateTroops(arg0: Troops): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTroops(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTroops(arg0);
            return result;
        }
    }
    async upgradeBase(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeBase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeBase(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
